[package]
name = "image-analyzer-script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-docker = "0.0.60"
ureq = { version = "2.6.2", features = [ "json" ] }
serde_json = "*"